### ISSUE TITLE
PR 요청시 충돌을 고려하지 않아도 되는지 질문드립니다.

### ISSUE THREAD

**Issue by hhtboy** [gunh0/whitehat-school-vulhub#42]
안녕하세요, PR 올리기 앞서 궁금한 점이 있어 질문 드립니다. 

서로 같은 주제에 대해서 PR을 올렸을  때, 동일한 디렉토리와 동일한 파일명을 가져 충돌이 발생합니다.
미리 올라온 PR이 승인된 후 개인 fork에서 pull을 받아 충돌을 해결하고 PR을 요청하는게 일반적인 것 같은데, 이를 고려하지 않고 PR을 요청해도 괜찮을지 질문 드립니다.

**Comment by gunh0** [comment]
제가 직접 하나씩 잡아가면서 과제를 평가하는 식으로 진행할 예정입니다.
